model:
  # NOTE MODEL IS ACTUALLY LOADED FROM JSON CONFIG FILE IN HUGGINGFACE REPO.
  # MODEL WAS TRAINED WITH THIS CONFIG. BEST NOT TO CHANGE.
  dim: 1024
  n_layers: 16
  head_dim: 64
  seqlen_t: false
  huber_c: null # [null uses MSE]
  input_dim: 32 
  encoder_input_dim: 32 
  encoder_output_dim: 32 
  encoder_latent_downsample_factor: 1   

  encoder_sliding_window: 65536 # big enough to not be used
  sliding_window: 65536 
  xattn_sliding_window: 65536 
  max_seqlen: 256                 # Max value for discretized {x,y,z} or tc - used with 4D-ROPE

  adaptive_loss_weighting: false  
  num_fine_time_pts: 32 
  rope_dim: 4 # 0 = NoPE, 1 = 1D-RoPE in seq-dim, 4 = 4D-RoPE in {x,y,z,tc}.
  rope_theta: 10000.0
  tok_idx_type: "{x,y,z,tc}"  # null, "t_coarse", "chan_id", "stack_arange_seqlen", "{x,y,z,tc}" 
  stft_global_sigma: 0.1 # Noising process std - should match signal std.
  dropout_vec_type: "zeros" # {"zero", "learnable"}


data:



  # (CW) comment out.
  # data_dir: ./tutorials/data/working/2_pt_input/
  export_dir: ./tutorials/data/working/3_pt_output/   # Where to save output .pt files after processing.
  # glob_filter: ["**/*.pt"] # this filters the dataset to only contain files with this string in it.

  # (CW) add this
  use_b2: false # If true, use Backblaze B2 for dataset loading, otherwise use local filesystem.
  use_v3: true # If true, use EEGDataset_v3 for dataset loading, with memaps and quality matrix
  filter_version: # "v2_notch" # options: {"v1_hpf",  "v2_notch",  "v3_bandpass"}
    - "v2_notch"
    - "v3_bandpass"
  min_quality_any: 0.1 # Default is 0.1
  min_quality_mean: 0.3 # Default is 0.3
  sample_duration_str: "30_seconds" # {"5_seconds", "10_seconds", "30_seconds", "5_sec_wt_short_third", "5_sec_wt_short_half", "10_to_30_sec_half", "10_to_30_sec_third", "30_seconds_fifths"}
  do_avg_ref: true # If true, do average reference before data normalization.
  z_score_type: "across_channel" # {"across_channel", "across_sample", "none"}
  data_dir: /data/groups/bci/datasets/v7_evalB # (CW) Not in podman env - was /workspace/bci/data/v7_evalB
  glob_filter: 
    - "*.json"

  mmap_sample_start: null #4096 #1024 # If not None, only sample from between this and stop in the mmap.
  mmap_sample_stop: null #42496 #5376 # If not None, only sample from between this and start in the mmap.
  skip_preepoched_data: false # If true, skip pre-epoched data.




  target_packed_seqlen: 10000 #100000            # Target seqlen for packed samples. This is essentially batch size.
  data_norm: 10.0 # this is the norm to divide the data by, to normalize it.
  data_clip: 1.0  # Clip data to this value after normalization.

  
  chan_num_filter: null # null or integer number of channels we want in each sample (another filter on input data)
  sample_rate: 256
  seq_len: 1280 # NOT REALLY USED ANYMORE. number of timepoints in each sample (fixed 5 sec samples at 256 Hz)
  num_fine_time_pts: 32 
  use_coarse_time: "A" # How to chop signals in to coarse-time, fine-time & channels using chop_and_reshape_signals.
  randomly_permute_sequence: false
  token_dropout_prob: 0.99 # Probability of applying channel dropout to the EEG signal during training.
  stft_global_sigma: 0.1 # Noising process std - should match signal std.

  num_bins_discretize_xyz_chan_pos: 50 # Number of bins to discretize channel positions to use in 4d-RoPE. (we used 50)
  chan_pos_xyz_extremes_type: "twelves" 

  # For dataloader.
  num_workers: 0              
  prefetch_factor: null          
  persistent_workers: false    
  pin_memory: false     

  shuffle: true              
  seed: 316                   